name: HardcoreSlimefun
author: TheBusyBiscuit
description: Slimefun but impossibly hard to beat
website: https://github.com/Slimefun-Addon-Community/HardcoreSlimefun

main: io.github.thebusybiscuit.hardcoreslimefun.HardcoreSlimefun
version: ${project.version}
api-version: 1.14

depend:
- Slimefun